[package]
name = "Tile-League"
version = "0.1.0"
authors = ["Kevin Wong <wong.kevin47@gmail.com>"]
build = "build.rs"

[dependencies]
ggez = { version = "0.4.3", features = ["cargo-resource-root"] }
nphysics2d = "0.9.0"
ncollide2d = "0.17"